#!/bin/bash

docker image build -t routerology/phpine:8.1 --platform linux/amd64,linux/arm64 -f Dockerfile_8.1 .
docker image build -t routerology/phpine:8.2 --platform linux/amd64,linux/arm64 -f Dockerfile_8.2 .
docker image build -t routerology/phpine:8.3 --platform linux/amd64,linux/arm64 -f Dockerfile_8.3 .
docker image build -t routerology/phpine:7.4 --platform linux/amd64,linux/arm64 -f Dockerfile_7 .
docker image build -t routerology/phpine:www --platform linux/amd64,linux/arm64 -f Dockerfile_www .
docker image tag routerology/phpine:8.3 routerology/phpine:latest
docker image push --all-tags routerology/phpine
