FROM alpine:3.21
LABEL my_name="daniel grigore"
LABEL my_youtube="https://www.youtube.com/@routerologyblog1111"


# Apache and PHP on Alpine Linux


RUN apk update && \
	apk add \
	tzdata \
	apache2 \
	apache2-utils \
	php82-apache2 \
	php82-bcmath \
	php82-bz2 \
	php82-calendar \
	php82-cgi \
	php82-common\
	php82-ctype\
	php82-curl\
	php82-dba\
	php82-dom\
	php82-embed\
	php82-enchant\
	php82-exif\
	php82-ffi\
	php82-fileinfo\
	php82-fpm\
	php82-ftp\
	php82-gd\
	php82-gettext\
	php82-gmp\
	php82-iconv\
	php82-imap\
	php82-intl\
	php82-ldap\
	php82-litespeed\
	php82-mbstring\
	php82-mysqli\
	php82-mysqlnd\
	php82-odbc\
	php82-opcache\
	php82-openssl\
	php82-pcntl\
	php82-pdo\
	php82-pdo_dblib\
	php82-pdo_mysql\
	php82-pdo_odbc\
	php82-pdo_sqlite\
	php82-pear\
	php82-pecl-decimal \
	php82-pecl-ds \
	php82-pecl-event \
	php82-pecl-grpc \
	php82-pecl-igbinary \
	php82-pecl-imagick \
	php82-pecl-lzf \
	php82-pecl-mcrypt \
	php82-pecl-memcache \
	php82-pecl-memcached \
	php82-pecl-msgpack \
	php82-pecl-pcov \
	php82-pecl-redis \
	php82-pecl-smbclient \
	php82-pecl-ssh2 \
	php82-pecl-timezonedb \
	php82-pecl-uploadprogress \
	php82-pecl-uuid \
	php82-pecl-vips \
	php82-pecl-xdebug \
	php82-pecl-xlswriter \
	php82-pecl-yaml \
	php82-pecl-zstd \
	php82-phar\
	php82-phpdbg\
	php82-posix\
	php82-pspell\
	php82-session\
	php82-shmop\
	php82-simplexml\
	php82-snmp\
	php82-soap\
	php82-sockets\
	php82-sodium\
	php82-spx \
	php82-sqlite3\
	php82-sysvmsg\
	php82-sysvsem\
	php82-sysvshm\
	php82-tidy\
	php82-tokenizer\
	php82-xml\
	php82-xmlreader\
	php82-xmlwriter\
	php82-xsl\
	php82-zip\
	&& rm -rf /var/lib/apt/lists/*


# Add the following extra tools if you need to do some troubleshooting on the container
# The same goes for the apache2-ssl also

RUN apk update && \
	apk add \
	net-tools \
	tcpdump \
	ca-certificates \
	iproute2 \
	wget \
	samba-client \
	shadow \
 	&& rm -rf /var/lib/apt/lists/* 

# The alpine container starts httpd as root, and after that it starts the child processes as "apache" user
# which has uid 100
# Lets modify that uid gid to 1000:1000

RUN 	usermod -u 1000 apache && \
	groupmod -g 1000 apache


# If we are using SSL, then we might need to add our ca to the trusted ssl chain
#COPY ssl/*.crt /usr/local/share/ca-certificates
#RUN update-ca-certificates

# We normally do not load the ssl module, so we delete the config file

RUN rm -f /etc/apache2/conf.d/ssl.conf

# Set the correct timezone


ENV TZ="Europe/Bucharest"


# We can copy the site content straight into the container but that's not a good practice.
# Look in the start script from the repo to see how to mount it as a volume at container start

# COPY www/ /var/www/localhost/htdocs

# The configuration files for PHP and HTTPD can be copied into the container
# but they can be very well overriden by mounting them at container start

# COPY php_ini/php.ini /etc/php82/php.ini
# COPY httpd_conf/httpd.conf /etc/apache2/httpd.conf

# The PID on this container is root/1, but the httpd workers/subprocesses are started with 100:101
# So if any files are to be created by the app inside, they will have that ownership

EXPOSE 80/tcp

ENTRYPOINT ["httpd","-DFOREGROUND"]

