#!/bin/bash
DOCKER_NAME=phpine-www
docker container run \
	--name ${DOCKER_NAME} \
	--hostname ${DOCKER_NAME} \
	--detach \
	--rm \
	--env TZ="Europe/Bucharest" \
	--restart unless-stopped \
	--mount type=bind,source=$(pwd)/www,destination=/var/www/localhost/htdocs/ \
	--mount type=bind,source=$(pwd)/log,destination=/var/www/logs/ \
	--mount type=bind,source=$(pwd)/httpd_conf/httpd.conf,destination=/etc/apache2/httpd.conf \
	--interactive \
	--tty \
	--publish 81:80 \
	routerology/phpine:latest


