#!/bin/bash

DOCKER_NAME=glpi_app
docker container run \
	--name ${DOCKER_NAME} \
	--hostname ${DOCKER_NAME}  \
	--detach \
	--rm \
	--interactive \
	--tty \
	--env TZ="Europe/Bucharest" \
	--publish 8080:80 \
	--init \
	routerology/glpi


# Pay attention to PHP version when mounting the php.ini config file


