#!/bin/bash

docker container run \
	--name php-8-alpine \
	--hostname php-8-alpine \
	--detach \
	--rm \
	--mount type=bind,source=$(pwd)/www,destination=/var/www/localhost/htdocs/ \
	--mount type=bind,source=$(pwd)/log,destination=/var/www/logs/ \
	--interactive \
	--tty \
	--publish 81:80 \
	alpine-8-php


	#--mount type=bind,source=$(pwd)/httpd_conf/httpd.conf,destination=/etc/apache2/httpd.conf \
