#!/bin/bash

docker container run -it \
	--detach \
	--rm \
	--name alpine_base \
	--hostname alpine_base \
	--mount type=bind,source=$(pwd)/log/admin,destination=/var/log/admin \
	routerology/alpine_base:latest
